"""Add 2 columns to bbdd

Revision ID: 7cf28401bbdc
Revises: f5597e6c2a97
Create Date: 2023-09-02 00:17:11.385006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7cf28401bbdc'
down_revision: Union[str, None] = 'f5597e6c2a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('res', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("' '"), nullable=False))
    op.add_column('partidos', sa.Column('enemy_res', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("' '"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'enemy_res')
    op.drop_column('partidos', 'res')
    # ### end Alembic commands ###
