"""table stats

Revision ID: c451ff7bd479
Revises: 7cf28401bbdc
Create Date: 2023-09-10 11:11:04.290000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c451ff7bd479'
down_revision: Union[str, None] = '7cf28401bbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.Column('effy_shots', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('penals', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('goals_in', sa.Integer(), nullable=False),
    sa.Column('effy_stops', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keeper', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
