"""Add 2 columns to bbdd

Revision ID: f5597e6c2a97
Revises: ce396307b909
Create Date: 2023-09-01 18:03:46.431573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f5597e6c2a97'
down_revision: Union[str, None] = 'ce396307b909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('poli', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Pabellon'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'poli')
    # ### end Alembic commands ###
